### ISSUE TITLE
Cannot open cabinet in crypt, a bug?

### ISSUE THREAD

**Issue by simmessa** [Slattstudio/BetrayedAllianceBook1#8]
Hello and thanks for such a great free game!

My issue is: I noticed I cannot open the cabinet in the crypt of the Carmyle family.

I tried what seems reasonable also from youtube vids like: 
> open cabinet

while standing close to it but I always get a message:
"You can't really do that now"

Am I doing this completely wrong? I don't know, I thought maybe it's some strange bug w. the parser.

Thank you and sorry for the trouble, feel free to close this if I'm wrong as I may as well be.
S.

**Comment by Slatteryan** [comment]
No trouble at all - in fact, thank you so much for bringing this to my attention! This is a game-breaking bug that I unintentionally introduced in the process of fixing a different bug. I have found the issue and will be updating the patch shortly.
Sorry for the unfortunate and abrupt end to the game.
The worst part is once I update the patch, your save files will not work on the "new" build. Very sorry.

**Comment by Slatteryan** [comment]
This issue has been fixed and v.1.3.3.1 is now available.

**Comment by EvilDennisR** [comment]
Thanks so much @simmessa ! Please provide a mailing address so we can provide double your money back for finding this critical bug in the game. 😆 

Here's the link for the new release: https://github.com/Slattstudio/BetrayedAllianceBook1/releases/tag/release-v1.3.3.1

Please feel free to come lurk on our discord!

**Comment by simmessa** [comment]
Hello again,

well NOW I feel like a hero! I have somehow managed to unblock the game for many future players! _*Proudly goes around smashing open each and every cabinet in the house*_ 

No worries, I won't be losing much progress due to save file incompatibility, I was just starting to get around in the game :)

Thank you for the prompt fix, keep 2x the amount of the refund to cover for future expenses! :D
